optimizer:
    lr: 2.5e-4
    eps: 1e-5
    clip_grad: .5

embedding:
    size: 32
    history_size: 16
    epochs: 1
    batch_size: 5000
    fc_size: 512
    lr: 5e-4
    tau: 0.1
    temporal_shift: 4
    spatial_shift: 4
    pretrain_steps: 1e5
    pretrain_epochs: 2000

agent:
    pi_clip: .1
    gamma: .99
    epochs: 3
    batch_size: 256
    ent_k: .01
    val_loss_k: 1
    gae_lambda: .95

train:
    total_steps: 1e7
    rollout_size: 128
    num_env: 8
    log_every: 10
