python -m train --env Alien
python -m train --env Amidar
python -m train --env Assault
python -m train --env Asterix
python -m train --env Asteroids
python -m train --env Atlantis
python -m train --env BankHeist
python -m train --env BattleZone
python -m train --env BeamRider
python -m train --env Bowling
python -m train --env Boxing
python -m train --env Breakout
python -m train --env Centipede
python -m train --env ChopperCommand
python -m train --env CrazyClimber
python -m train --env DemonAttack
python -m train --env DoubleDunk
python -m train --env Enduro
python -m train --env FishingDerby
python -m train --env Freeway
python -m train --env Frostbite
python -m train --env Gopher
python -m train --env Gravitar
python -m train --env IceHockey
python -m train --env Jamesbond
python -m train --env Kangaroo
python -m train --env Krull
python -m train --env KungFuMaster
python -m train --env MontezumaRevenge
python -m train --env MsPacman
python -m train --env NameThisGame
python -m train --env Pitfall
python -m train --env Pong
python -m train --env PrivateEye
python -m train --env Qbert
python -m train --env Riverraid
python -m train --env RoadRunner
python -m train --env Robotank
python -m train --env Seaquest
python -m train --env SpaceInvaders
python -m train --env StarGunner
python -m train --env Tennis
python -m train --env TimePilot
python -m train --env Tutankham
python -m train --env UpNDown
python -m train --env Venture
python -m train --env VideoPinball
python -m train --env WizardOfWor
python -m train --env Zaxxon
