optimizer:
    lr: 2.5e-4
    eps: 1e-5
    clip_grad: .5

embedding:
    method: iic
    use_rnn: False
    concat_actions: True
    n_step: 5
    size: 16
    stack: 32
    epochs: 4

agent:
    pi_clip: .1
    gamma: .99
    epochs: 4
    batch_size: 256
    ent_k: .01
    val_loss_k: 1
    gae_lambda: .95

env:
    name: MsPacmanNoFrameskip-v4
    num: 8

train:
    steps: 10000
    rollout_size: 128
    log_every: 1
    checkpoint_every: 10000
    checkpoint_name: models/iic16_{n_iter}.pt
