optimizer:
    lr: 5e-5
    eps: 1e-5
    clip_grad: 1

conv:
    channels: [32, 64, 64]
    kernel_size: [8, 4, 3]
    stride: [4, 2, 1]

model:
    hidden_sizes: [512]

agent:
    pi_clip: .1
    gamma: .99
    epochs: 10
    batch_size: 512
    ent_k: .01
    val_loss_k: .1
    gae_lambda: .95

env:
    name: MsPacmanNoFrameskip-v4
    num: 100

train:
    steps: 20000
    rollout_size: 64
    log_every: 1
    checkpoint_every: 500
    checkpoint_name: models/pacman_{n_iter}.pt
